version: '3.8'

services:

  backend:

    build: ./backend
    
    ports:
      - "5000:5000"
    
    volumes:
      - ./backend:/app
    
    environment:
      - DB_HOST=postgres-db # O nome do serviço do banco de dados
      - POSTGRES_DB=tarefas_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    
    depends_on:
      - postgres-db

  # Serviço do Banco de Dados (PostgreSQL)
  postgres-db:
   
    image: postgres:14-alpine

    environment:
      - POSTGRES_DB=tarefas_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  # Serviço do Frontend (Servidor Web Nginx)
  frontend:

    image: nginx:stable-alpine

    ports:
      - "8080:80"

    volumes:
      - ./frontend:/usr/share/nginx/html

    depends_on:
      - backend
      
volumes:
  postgres_data:

